language: cpp

compiler:
  - gcc
  - clang

env:
  - USE_SYSTEM_CURL=ON USE_SYSTEM_CMAKE=ON
  - USE_SYSTEM_CURL=OFF USE_SYSTEM_CMAKE=ON
  - USE_SYSTEM_CURL=OFF USE_SYSTEM_CMAKE=OFF
  - USE_SYSTEM_CURL=ON USE_SYSTEM_CMAKE=OFF

sudo: required

before_install:
  - sudo apt-get update

install:
  - if [ "$USE_SYSTEM_CURL" == "OFF" ]; then sudo apt-get remove curl libcurl3; fi
  - if [ "$USE_SYSTEM_CMAKE" == "OFF" ]; then sudo apt-get remove cmake && wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz && tar -xzf cmake-3.2.1.tar.gz && cd cmake-3.2.1 && ./bootstrap > /dev/null && make -j8 > /dev/null && sudo make install && cd .. && rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz; else sudo apt-get install -y cmake; fi

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
