language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install cmake; fi

os:
  - linux
  - osx

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
