name: Build Debian Package
on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'The optional semantic version number. If not supplied the branch/tag will be used.'
        type: string
  pull_request:

jobs:
  package-ubuntu-latest-amd64:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        submodules: true
        path: cpr

      # Install packages necessary for building libcpr and package
    - name: "Update package list"
      run: sudo apt update
    - name: "Install cpr dependencies"
      run: sudo apt install -y libssl-dev libcurl4-openssl-dev
    - name: "Install building tools"
      run: sudo apt install -y cmake debmake devscripts debhelper

    - name: Set version based on input
      if: ${{ inputs.version }}
      run: echo "RELEASE_VERSION=${{ inputs.version }}" >> "$GITHUB_ENV"
    - name: Set version based on ref
      if: ${{ !inputs.version }}
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
    - name: Print Version
      run: echo "deb version will be '${{ env.RELEASE_VERSION }}'"
      # Build package of runtime library
    - name: "Package build of runtime library"
      env: 
        VERSION: ${{ env.RELEASE_VERSION }}
      run: bash cpr/package-build/build-package.sh cpr

    - name: "Upload deb-packages"
      uses: actions/upload-artifact@v4
      with:
        name: artifact-deb
        path: ./*.deb
