name: CI
on:
  push:
      branches: [ build-deb-package ]
      # tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
      branches: [ build-deb-package ]
      # tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  package-debian-latest-amd64:
    runs-on: debian-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        submodules: true
        path: cpr

      # Install packages necessary for building libcpr and package
    - name: "Update package list"
      run: sudo apt update
    - name: "Install cpr dependencies"
      run: sudo apt install libssl-dev libcurl4-openssl-dev
    - name: "Install building tools"
      run: sudo apt install debmake devscripts

      # Build packages of runtime and development library
    - name: "Package build of runtime library"
      env: 
        VERSION: ${{ github.event.ref }}
      run: bash cpr/package-build/build-package.sh cpr
    - name: "Package build of development library"
      env: 
        VERSION: ${{ github.event.ref }}
      run: bash cpr/package-build/build-dev-package.sh cpr

    - name: "Upload deb-packages"
      uses: actions/upload-artifact@v3
      with:
        name: artifact-deb
        path: ./*.deb

